<?php

namespace AppBundle\Repository;

/**
 * ExpProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpProRepository extends \Doctrine\ORM\EntityRepository
{
}
