<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray($key,$dir,$search=null)
    {
        $qb =  $this->createQueryBuilder('q')
            ->Orderby('q.'.$key,$dir);
        if ($search != null){
            $qb->where('q.title like :search');
            $qb->setParameter('search','%'.$search.'%');
        }

         return $qb->getQuery()
            ->getArrayResult();
    }
}
